# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

# z-jump
. ~/z/z.sh

# Auto suggestion
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept

# Aliases
alias gitconfig='code-insiders ~/.gitconfig'
alias zprof='code-insiders ~/.zprofile'
alias zshrc='code-insiders ~/.zshrc'

alias st='git status'
alias co='git checkout'
alias pr='git pull --rebase'
alias lg='git log'
alias rc='git rc'
alias diff='git diff'

alias ssn='python3 ~/scripts/ssngenerator.py | pbcopy'
alias uuid="python3 -c \"import uuid; print(uuid.uuid4(), end='')\" | pbcopy"
alias code="code-insiders"

scalekube() {
	kubectl scale rc $1 --replicas=0 && kubectl scale rc $1 --replicas=1
}

updateimgkube() {
	kubectl set image replicationcontroller/$1 $1=eu.gcr.io/bynk-146312/$1:$2 && kubectl scale rc $1 --replicas=0 && kubectl scale rc $1 --replicas=1
}

bindkey "^X^_" redo
